store/urls.py
from django.urls import path

from . import views

app_name = 'store'
urlpatterns = [
    path('', views.index, name='index'),
    path('detail/<int:product_id>/', views.detail, name='detail'),
    path('basket/', views.basket, name='basket'),
    path('add/<int:product_id>/', views.add_product_to_s_basket, name='add_product_to_s_basket'),
    path('del/<int:product_id>/', views.delete_product_from_s_basket, name='delete_product_from_s_basket'),
    path('clear/', views.clear_s_basket, name='clear_s_basket'),
]

store_main/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', include('store.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

store/models.py
from django.db import models

class Product(models.Model):
    in_stock = models.BooleanField(default=False)
    name = models.CharField(max_length=200)
    price = models.IntegerField(default=0)
    description = models.CharField(max_length=211)
    image1 = models.ImageField(upload_to='images', null=True, blank=True) #default="picture.png"
    image2 = models.ImageField(upload_to='images', null=True, blank=True)
    image3 = models.ImageField(upload_to='images', null=True, blank=True) 
    video = models.FileField(upload_to='videos', null=True, blank=True)

    def __str__(self):
    	return self.name

    def delete(self, *args, **kwargs):
        self.image1.delete()
        self.image2.delete()
        self.image3.delete()
        self.video.delete()
        super().delete(*args, **kwargs)

store/views.py
from django.shortcuts import render, get_object_or_404
from django.views.decorators.http import require_http_methods
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib import messages
from django.urls import reverse

from .models import Product


def create_shopping_basket(request):
    # создать корзину если еще нету
    s_basket_list = request.session.get('s_basket')
    if not s_basket_list:
        s_basket_list = []
    return s_basket_list

def basket_value_and_sum(request):
    b_sum = 0
    products = Product.objects.filter(in_stock=True)
    s_basket_list = create_shopping_basket(request)
    
    products_ids = [i.id for i in products]
    for product_id in s_basket_list:
        # синхронизировать корзину с товарами в наличии
        if product_id not in products_ids:
           s_basket_list.remove(product_id) 
        else:
            try:
                # сложить сумму товаров в корзине
                b_sum += Product.objects.get(id=product_id).price
            except Product.DoesNotExist:
                pass

    request.session['s_basket'] = s_basket_list

    return b_sum


def index(request):
    # in_stock=True в наличии
    products_for_sale =reversed(Product.objects.filter(in_stock=True))
    s_basket_sum = basket_value_and_sum(request)

    context = {
    'products_for_sale': products_for_sale,
    's_basket_sum': s_basket_sum,
    }
    return render(request, 'store/index.html', context)


def detail(request, product_id):
    current_product = get_object_or_404(Product, pk=product_id)
    s_basket_sum = basket_value_and_sum(request)

    context = {
        'current_product': current_product,
        's_basket_sum': s_basket_sum,
    }
    return render(request, 'store/detail.html', context)

def basket(request):
    # корзина товаров
    s_basket_list = request.session.get('s_basket')
    products_in_basket = Product.objects.filter(in_stock=True, pk__in=s_basket_list)
    s_basket_sum = basket_value_and_sum(request)

    context = {
        'products_in_basket': products_in_basket,
        's_basket_sum': s_basket_sum,
    }
    return render(request, 'store/basket.html', context)


@require_http_methods(["POST"])
def add_product_to_s_basket(request, product_id):
    # add product to shopping basket

    # существует ли продукт, если нет 404
    get_object_or_404(Product, pk=product_id)

    s_basket_list = create_shopping_basket(request)
        
    if product_id in s_basket_list:
        return HttpResponse('404, already added')
    
    s_basket_list.append(product_id)
    request.session['s_basket'] = s_basket_list
    
    next = request.META.get('HTTP_REFERER')
    messages.error(request, '+ корзина')
    return HttpResponseRedirect(next)


@require_http_methods(["POST"])
def delete_product_from_s_basket(request, product_id):
    # delete one from shopping basket

    # существует ли продукт, если нет 404
    get_object_or_404(Product, pk=product_id)
    
    s_basket_list = request.session.get('s_basket')
    
    s_basket_list.remove(product_id)
    request.session['s_basket'] = s_basket_list
    
    return HttpResponseRedirect(reverse('store:basket'))
        

@require_http_methods(["POST"])       
def clear_s_basket(request):
    try:
        del request.session['s_basket']
    except KeyError:
        pass

    return HttpResponseRedirect(reverse('store:index'))

store/templates/store/basket.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <title>Корзина</title>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'store/css/bootstrap.min.css' %}" rel="stylesheet">

    <style>
        .bd-placeholder-img {
          font-size: 1.125rem;
          text-anchor: middle;
          -webkit-user-select: none;
          -moz-user-select: none;
          user-select: none;
        }
  
        @media (min-width: 768px) {
          .bd-placeholder-img-lg {
            font-size: 3.5rem;
          }
        }
  
        .header{background:rgb(0, 178, 255);color:#fff;}
        #lblCartCount {
            font-size: 12px;
            background: #ff0000;
            color: #fff;
            padding: 0 5px;
            vertical-align: top;
            margin-left: -10px;
        }
        .badge {
          padding-left: 9px;
          padding-right: 9px;
          -webkit-border-radius: 9px;
          -moz-border-radius: 9px;
          border-radius: 9px;
        }
  
        .label-warning[href],
        .badge-warning[href] {
          background-color: #c67605;
        }
  
      </style>

  <!-- Custom styles for this template -->
  <link href="{% static 'store/css/carousel.css' %}" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>
  <body>
    <main>  
      
      <br><br>

      <div class="container marketing">
        
         <!-- Three columns of text below the carousel -->
        <div class="row">
            {% if request.session.s_basket|length != 0 %}
                {% for product in products_in_basket %}
                    <div class="col-lg-4">
                        <a href="{% url 'store:detail' product.id %}">
                          <img class="rounded-circle" src="{{ product.image1.url }}" alt="Generic placeholder image" width="190" height="190">
                        </a>
                        <h2>{{ product.name }}</h2>
                        <h2>{{ product.price }}</h2>
                        <p>{{ product.description }}</p>
                        {% if request.session.s_basket|length != 1 %}
                          <form action="{% url 'store:delete_product_from_s_basket' product.id %}" method="post">
                            {% csrf_token %}
                            <p><input class="btn btn-secondary" type="submit" value="Удалить"></p>
                          </form>
                        {% else %}                                           
                          <form action="{% url 'store:clear_s_basket' %}" method="post">
                            {% csrf_token %}
                            <p><input class="btn btn-secondary" type="submit" value="Удалить"></p>
                          </form>
                        {% endif %}
                    </div><!-- /.col-lg-4 -->
                {% endfor %}

            {% else %}
                <hr class="featurette-divider">
                <h2 class="featurette-heading text-center">Корзина пуста</h2>
                <br>
                <h4 class="text-muted text-center">
                    <a  href="{% url 'store:index' %}">Главная</a>
                </h4>
            {% endif %}
            
        </div><!-- /.row -->
        <hr class="featurette-divider">
        <div class="row">
            <div class="col-lg-4">
                <h2>Товаров: {{ request.session.s_basket|length }}</h2>
            </div><!-- /.col-lg-4 -->
            <div class="col-lg-4">
                <h2>На сумму: <span class="text-success">{{ s_basket_sum }} ₽</span></h2>
            </div><!-- /.col-lg-4 -->
            <div class="col-lg-4">
                <p><a class="btn btn-secondary" href="#" role="button">Оформить</a></p>
            </div><!-- /.col-lg-4 -->
        </div>
            
        
      </div><!-- /.container -->
      <br>
    </main>
    
    <!-- sticky footer -->
    <nav class="navbar fixed-bottom navbar-expand-sm navbar-dark bg-dark">
        <div class="container-fluid">
          <a style="font-size: 24px;" class="navbar-brand" href="{% url 'store:index' %}">Магазин</a>
          <ul class="navbar-nav">
            {% if request.session.s_basket|length > 0 %}
              <li class="navbar-brand">
                <a class="nav-link" aria-current="page" href="#">
                    <i class="fa" style="font-size:35px">&#xf07a;</i>
                    <span class='badge badge-warning' id='lblCartCount'>{{ request.session.s_basket|length }}</span>
                    <span class="text-success">{{ s_basket_sum }} ₽</span>
                </a>
              </li>
            {% else %}
              <li class="navbar-brand text-muted">
                <span class="nav-link" aria-current="page">
                  <i class="fa" style="font-size:24px">&#xf07a;</i>
                  <span class="text-success">{{ s_basket_sum }} ₽</span>
                </span>
              </li>
            {% endif %}
          </ul>
        </div>
      </nav>

    <script src="{% static 'store/js/bootstrap.bundle.min.js' %}"></script>
  </body>
</html>

store/templates/store/detail.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <title>{{ current_product.name }}</title>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'store/css/bootstrap.min.css' %}" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }
      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .header{background:rgb(0, 178, 255);color:#fff;}
      #lblCartCount {
          font-size: 12px;
          background: #ff0000;
          color: #fff;
          padding: 0 5px;
          vertical-align: top;
          margin-left: -10px;
      }
      .badge {
        padding-left: 9px;
        padding-right: 9px;
        -webkit-border-radius: 9px;
        -moz-border-radius: 9px;
        border-radius: 9px;
      }

      .label-warning[href],
      .badge-warning[href] {
        background-color: #c67605;
      }

      .carousel-inner > .carousel-item > img {
      height: 100vh;
      }
      
    </style>
    

  <!-- Custom styles for this template -->
  <link href="{% static 'store/css/carousel.css' %}" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>
  <body>
    <main>  
      
      <br><br>

      <div class="container marketing">
        <div class="row featurette">

          <div class="col-md-6">
            <video width="100%" height="70%" autoplay muted loop>
              <source src="{{ current_product.video.url }}" type="video/mp4">
              <!--<source src="movie.ogg" type="{{ current_product.video.url }}">-->
            Your browser does not support the video tag.
            </video>
            <div class="col px-md-5">{{ current_product.description }}</div>
            <!--ahuennoe reshenie-->
            <br><br><br><br><br><br>
            <br><br><br><br><br><br>
          </div>

          <div class="col-md-6">
            <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
              <div class="carousel-indicators">
                <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
                <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
                <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
              </div>
              <div class="carousel-inner">
                <div class="carousel-item active">
                  <a data-bs-toggle="modal" data-bs-target="#exampleModal1" href="">
                    <img src="{{ current_product.image1.url }}" class="d-block w-100" alt="...">
                  </a>
                </div>
                <div class="carousel-item">
                  <a data-bs-toggle="modal" data-bs-target="#exampleModal2" href="">
                    <img src="{{ current_product.image2.url }}" class="d-block w-100" alt="...">
                  </a>
                </div>
                <div class="carousel-item">
                  <a data-bs-toggle="modal" data-bs-target="#exampleModal3" href="">
                    <img src="{{ current_product.image3.url }}" class="d-block w-100" alt="...">
                  </a>
                </div>
              </div>
              <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions"  data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
              </button>
              <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions"  data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
              </button>
            </div>

            <h2>{{ current_product.name }}</h2>
            <h2>Стоимость: <span class="text-success">{{ current_product.price }} ₽</span></h2>
            {% if not request.session.s_basket %}
              <form action="{% url 'store:add_product_to_s_basket' current_product.id %}" method="post">
                {% csrf_token %}
                <input type="hidden" name="next" value="{{ request.path }}">
                <input class="btn btn-success" type="submit" value="В Корзину">
              </form>
            {% elif current_product.id not in request.session.s_basket %}
              <form action="{% url 'store:add_product_to_s_basket' current_product.id %}" method="post">
                {% csrf_token %}
                <input type="hidden" name="next" value="{{ request.path }}">
                <input class="btn btn-success" type="submit" value="В Корзину">
              </form>
              {% elif current_product.id in request.session.s_basket %}
                <h6 class="text-muted">Товар добавлен в корзину</h6>
            {% endif %}
          </div>

        </div>
        <!-- /END THE FEATURETTES -->
      </div><!-- /.container -->
      
      <br><br>

    </main>

    <!-- Modals -->
    <div class="modal fade" id="exampleModal1" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-lg">.
        <div class="modal-content">
          <div style="border: none;" class="modal-header">
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <img class="img-fluid mx-auto" src="{{ current_product.image1.url }}">
          </div>   
        </div>
      </div>
    </div>

    <div class="modal fade" id="exampleModal2" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-lg">.
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <img class="img-fluid mx-auto" src="{{ current_product.image2.url }}">
          </div>   
        </div>
      </div>
    </div>

    <div class="modal fade" id="exampleModal3" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-lg">.
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <img class="img-fluid mx-auto" src="{{ current_product.image3.url }}">
          </div>   
        </div>
      </div>
    </div>

    <!-- sticky footer -->
    <nav class="navbar fixed-bottom navbar-expand-sm navbar-dark bg-dark">
      <div class="container-fluid">
        <a style="font-size: 24px;" class="navbar-brand" href="{% url 'store:index' %}">Магазин</a>
        {% if messages %}
          {% for message in messages %}
          <small style="color:white;">{{ message }}</small>
          {% endfor %}
        {% endif %}
        <ul class="navbar-nav">
          {% if request.session.s_basket|length > 0 %}
            <li class="navbar-brand">
              <a class="nav-link" aria-current="page" href="{% url 'store:basket' %}">
                  <i class="fa" style="font-size:35px">&#xf07a;</i>
                  <span class='badge badge-warning' id='lblCartCount'>{{ request.session.s_basket|length }}</span>
                  <span class="text-success">{{ s_basket_sum }} ₽</span>
              </a>
            </li>
          {% else %}
            <li class="navbar-brand text-muted">
              <span class="nav-link" aria-current="page">
                <i class="fa" style="font-size:35px">&#xf07a;</i>
                <span class="text-success">{{ s_basket_sum }} ₽</span>
              </span>
            </li>
          {% endif %}
        </ul>
      </div>
    </nav>
    <script src="{% static 'store/js/bootstrap.bundle.min.js' %}"></script>
  </body>
</html>

store/templates/store/index.html
{% load static %}
<!doctype html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <title>Магазин</title>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'store/css/bootstrap.min.css' %}" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .header{background:rgb(0, 178, 255);color:#fff;}
      #lblCartCount {
          font-size: 12px;
          background: #ff0000;
          color: #fff;
          padding: 0 5px;
          vertical-align: top;
          margin-left: -10px;
      }
      .badge {
        padding-left: 9px;
        padding-right: 9px;
        -webkit-border-radius: 9px;
        -moz-border-radius: 9px;
        border-radius: 9px;
      }

      .label-warning[href],
      .badge-warning[href] {
        background-color: #c67605;
      }

      .carousel-inner > .carousel-item > img {
      height: 100vh;
      }
    </style>

    <!-- Custom styles for this template -->
    <link href="{% static 'store/css/carousel.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>
  <body>

    <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
      <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
      </div>
      <div class="carousel-inner">
        <div class="carousel-item active">
          <img src="{% static 'store/images/арт-красивые-картинки-улица-город-1828365.jpeg' %}" class="d-block w-100" alt="...">
          <div class="carousel-caption d-none d-md-block">
            <h5>First slide label</h5>
            <p>Some representative placeholder content for the first slide.</p>
          </div>
        </div>
        <div class="carousel-item">
          <img src="{% static 'store/images/cherry-tree-anime-5d-2560x1700.jpg' %}" class="d-block w-100" alt="...">
          <div class="carousel-caption d-none d-md-block">
            <h5>Second slide label</h5>
            <p>Some representative placeholder content for the second slide.</p>
          </div>
        </div>
        <div class="carousel-item">
          <img src="{% static 'store/images/neon-ulitsa-noch-ogni-vyveska-svet.jpg' %}" class="d-block w-100" alt="...">
          <div class="carousel-caption d-none d-md-block">
            <h5>Third slide label</h5>
            <p>Some representative placeholder content for the third slide.</p>
          </div>
        </div>
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions"  data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions"  data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>

    <main>

      <div class="container marketing">
        
        <!-- START THE FEATURETTES -->
        {% if products_for_sale %}
          {% for product in products_for_sale %}
            {% if product.id|divisibleby:"2" %}
              <div class="row featurette">
                <div class="col-md-8 order-md-2">
                  <h2 class="featurette-heading">{{ product.name }}
                    <br>
                    <span class="text-muted">{{ product.price }}</span>
                  </h2>
                  <p class="lead">{{ product.description }}</p>
                </div>
                
                <div class="col-md-4 order-md-1">
                  <a href="{% url 'store:detail' product.id %}">
                    <img width="400" class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" src="{{ product.image1.url }}" />
                  </a>
                </div>
        
              </div>
              <hr class="featurette-divider">
            {% else %}
              <div class="row featurette">
                <div class="col-md-8">
                  <h2 class="featurette-heading">{{ product.name }}
                    <br>
                    <span class="text-muted">{{ product.price }}</span>
                  </h2>
                  <p class="lead">{{ product.description }}</p>
                </div>
                <div class="col-md-4">
                  <a href="{% url 'store:detail' product.id %}">
                    <img width="400" class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" src="{{ product.image1.url }}" />
                  </a>
                </div>
              </div>
              <hr class="featurette-divider">
            {% endif %}
          {% endfor %}
        {% else %}
        <h2 class="featurette-heading text-center">Товаров пока нет<br><span class="text-muted">Заходи позже</span></h2>
        <hr class="featurette-divider">
        {% endif %}

        <!-- /END THE FEATURETTES -->
      </div><!-- /.container -->
    </main>

    <!-- sticky footer -->
    <nav class="navbar fixed-bottom navbar-expand-sm navbar-dark bg-dark">
      <div class="container-fluid">
        <a style="font-size: 24px;" class="navbar-brand" href="#">Магазин</a>
        <ul class="navbar-nav">
          {% if request.session.s_basket|length > 0 %}
            <li class="navbar-brand">
              <a class="nav-link" aria-current="page" href="{% url 'store:basket' %}">
                  <i class="fa" style="font-size:35px">&#xf07a;</i>
                  <span class='badge badge-warning' id='lblCartCount'>{{ request.session.s_basket|length }}</span>
                  <span class="text-success">{{ s_basket_sum }} ₽</span>
              </a>
            </li>
          {% else %}
            <li class="navbar-brand text-muted">
              <span class="nav-link" aria-current="page">
                <i class="fa" style="font-size:35px">&#xf07a;</i>
                <span class="text-success">{{ s_basket_sum }} ₽</span>
              </span>
            </li>
          {% endif %}
        </ul>
      </div>
    </nav>

    <script src="{% static 'store/js/bootstrap.bundle.min.js' %}"></script>
  </body>
</html>